# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _Listas
else:
    import _Listas

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class ListaUsuario(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Listas.ListaUsuario_swiginit(self, _Listas.new_ListaUsuario())

    def agregarlista(self, id, nick, _pass, mon, edad):
        return _Listas.ListaUsuario_agregarlista(self, id, nick, _pass, mon, edad)

    def obtener(self):
        return _Listas.ListaUsuario_obtener(self)

    def mostrarlista(self):
        return _Listas.ListaUsuario_mostrarlista(self)

    def verificar(self, nick, _pass):
        return _Listas.ListaUsuario_verificar(self, nick, _pass)

    def editar(self, res, nick, _pass, mon, edad):
        return _Listas.ListaUsuario_editar(self, res, nick, _pass, mon, edad)

    def eliminar(self, res):
        return _Listas.ListaUsuario_eliminar(self, res)

    def encriptar(self, _pass):
        return _Listas.ListaUsuario_encriptar(self, _pass)

    def obtemonedas(self, res, _pass):
        return _Listas.ListaUsuario_obtemonedas(self, res, _pass)

    def obtedad(self, res, _pass):
        return _Listas.ListaUsuario_obtedad(self, res, _pass)

    def agregarmovipila(self):
        return _Listas.ListaUsuario_agregarmovipila(self)

    def ordeascen(self):
        return _Listas.ListaUsuario_ordeascen(self)

    def ordedescen(self):
        return _Listas.ListaUsuario_ordedescen(self)

    def graficadoble(self):
        return _Listas.ListaUsuario_graficadoble(self)
    __swig_destroy__ = _Listas.delete_ListaUsuario

# Register ListaUsuario in _Listas:
_Listas.ListaUsuario_swigregister(ListaUsuario)

class ColaTutorial(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Listas.ColaTutorial_swiginit(self, _Listas.new_ColaTutorial())

    def insertar(self, x, y, indi):
        return _Listas.ColaTutorial_insertar(self, x, y, indi)

    def eliminar(self):
        return _Listas.ColaTutorial_eliminar(self)

    def mostrar(self):
        return _Listas.ColaTutorial_mostrar(self)

    def graficar(self):
        return _Listas.ColaTutorial_graficar(self)
    __swig_destroy__ = _Listas.delete_ColaTutorial

# Register ColaTutorial in _Listas:
_Listas.ColaTutorial_swigregister(ColaTutorial)

class ListaMovimientos(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _Listas.ListaMovimientos_swiginit(self, _Listas.new_ListaMovimientos())

    def agregar(self):
        return _Listas.ListaMovimientos_agregar(self)
    __swig_destroy__ = _Listas.delete_ListaMovimientos

# Register ListaMovimientos in _Listas:
_Listas.ListaMovimientos_swigregister(ListaMovimientos)

class ListaCategoria(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    inicio = property(_Listas.ListaCategoria_inicio_get, _Listas.ListaCategoria_inicio_set)
    fin = property(_Listas.ListaCategoria_fin_get, _Listas.ListaCategoria_fin_set)
    cabecera = property(_Listas.ListaCategoria_cabecera_get, _Listas.ListaCategoria_cabecera_set)

    def __init__(self):
        _Listas.ListaCategoria_swiginit(self, _Listas.new_ListaCategoria())

    def agregarCate(self, dato):
        return _Listas.ListaCategoria_agregarCate(self, dato)

    def mostrarCate(self):
        return _Listas.ListaCategoria_mostrarCate(self)

    def getCate(self, dato):
        return _Listas.ListaCategoria_getCate(self, dato)

    def agregarArti(self, id, categoria, precio, nom, src):
        return _Listas.ListaCategoria_agregarArti(self, id, categoria, precio, nom, src)

    def mostrarArti(self):
        return _Listas.ListaCategoria_mostrarArti(self)

    def getPrecio(self, id):
        return _Listas.ListaCategoria_getPrecio(self, id)

    def graficarListas(self):
        return _Listas.ListaCategoria_graficarListas(self)

    def ordenamietno(self):
        return _Listas.ListaCategoria_ordenamietno(self)
    __swig_destroy__ = _Listas.delete_ListaCategoria

# Register ListaCategoria in _Listas:
_Listas.ListaCategoria_swigregister(ListaCategoria)



